-- Insert 50 new general knowledge questions
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
('Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'B'),
('What is the largest ocean on Earth?', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'D'),
('Who wrote "Romeo and Juliet"?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 'B'),
('What is the capital of Japan?', 'Beijing', 'Seoul', 'Tokyo', 'Bangkok', 'C'),
('Which element has the chemical symbol "O"?', 'Gold', 'Oxygen', 'Silver', 'Iron', 'B'),
('What is the largest mammal in the world?', 'African Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus', 'B'),
('Which country is home to the kangaroo?', 'South Africa', 'Australia', 'New Zealand', 'Brazil', 'B'),
('What is the main ingredient in guacamole?', 'Tomato', 'Avocado', 'Onion', 'Lime', 'B'),
('Who painted the "Starry Night"?', 'Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dali', 'B'),
('What is the currency of the United Kingdom?', 'Euro', 'Dollar', 'Pound Sterling', 'Yen', 'C'),
('Which planet is closest to the Sun?', 'Venus', 'Mars', 'Mercury', 'Earth', 'C'),
('What is the largest desert in the world?', 'Gobi Desert', 'Sahara Desert', 'Antarctic Desert', 'Arabian Desert', 'C'),
('Who wrote "Harry Potter"?', 'Stephen King', 'J.K. Rowling', 'George R.R. Martin', 'Roald Dahl', 'B'),
('What is the capital of Canada?', 'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 'C'),
('Which animal is known as the "King of the Jungle"?', 'Tiger', 'Lion', 'Elephant', 'Gorilla', 'B'),
('What is the largest organ in the human body?', 'Heart', 'Brain', 'Liver', 'Skin', 'D'),
('Which country is known as the Land of the Rising Sun?', 'China', 'Korea', 'Japan', 'Thailand', 'C'),
('What is the main ingredient in bread?', 'Sugar', 'Flour', 'Salt', 'Yeast', 'B'),
('Who wrote "The Little Prince"?', 'Antoine de Saint-Exupéry', 'Victor Hugo', 'Albert Camus', 'Jean-Paul Sartre', 'A'),
('What is the currency of Japan?', 'Won', 'Yen', 'Ringgit', 'Baht', 'B'),
('Which planet has the most moons?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'B'),
('What is the largest rainforest in the world?', 'Congo Rainforest', 'Amazon Rainforest', 'Daintree Rainforest', 'Borneo Rainforest', 'B'),
('Who painted the "Last Supper"?', 'Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello', 'B'),
('What is the capital of Brazil?', 'Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador', 'C'),
('Which animal is the fastest land mammal?', 'Lion', 'Cheetah', 'Gazelle', 'Antelope', 'B'),
('What is the smallest bone in the human body?', 'Femur', 'Tibia', 'Stapes', 'Radius', 'C'),
('Which country is known as the Land of Fire and Ice?', 'Norway', 'Sweden', 'Iceland', 'Finland', 'C'),
('What is the main ingredient in sushi?', 'Rice', 'Noodles', 'Bread', 'Potato', 'A'),
('Who wrote "Alice in Wonderland"?', 'J.M. Barrie', 'Lewis Carroll', 'Roald Dahl', 'Beatrix Potter', 'B'),
('What is the currency of China?', 'Yen', 'Won', 'Yuan', 'Ringgit', 'C'),
('Which planet is known as the Evening Star?', 'Mars', 'Venus', 'Jupiter', 'Saturn', 'B'),
('What is the largest coral reef system in the world?', 'Great Barrier Reef', 'Belize Barrier Reef', 'New Caledonia Barrier Reef', 'Red Sea Coral Reef', 'A'),
('Who painted the "Scream"?', 'Vincent van Gogh', 'Pablo Picasso', 'Edvard Munch', 'Salvador Dali', 'C'),
('What is the capital of South Africa?', 'Johannesburg', 'Cape Town', 'Pretoria', 'Durban', 'C'),
('Which animal is the largest living reptile?', 'Komodo Dragon', 'Saltwater Crocodile', 'Green Anaconda', 'Nile Crocodile', 'B'),
('What is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Platinum', 'C'),
('Which country is known as the Land of a Thousand Lakes?', 'Sweden', 'Norway', 'Finland', 'Denmark', 'C'),
('What is the main ingredient in chocolate?', 'Sugar', 'Cocoa', 'Milk', 'Vanilla', 'B'),
('Who wrote "The Hobbit"?', 'C.S. Lewis', 'J.R.R. Tolkien', 'George R.R. Martin', 'Terry Pratchett', 'B'),
('What is the currency of Russia?', 'Euro', 'Dollar', 'Ruble', 'Yen', 'C'),
('Which planet is known as the Blue Planet?', 'Venus', 'Mars', 'Earth', 'Neptune', 'C'),
('What is the largest waterfall in the world?', 'Niagara Falls', 'Victoria Falls', 'Angel Falls', 'Iguazu Falls', 'C'),
('Who painted the "Girl with a Pearl Earring"?', 'Vincent van Gogh', 'Johannes Vermeer', 'Rembrandt', 'Claude Monet', 'B'),
('What is the capital of Egypt?', 'Alexandria', 'Giza', 'Cairo', 'Luxor', 'C'),
('Which animal is the largest living bird?', 'Emu', 'Ostrich', 'Cassowary', 'Albatross', 'B'),
('What is the most abundant element in the Earth''s atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 'C'),
('Which country is known as the Land of the Midnight Sun?', 'Sweden', 'Norway', 'Finland', 'Iceland', 'B'),
('What is the main ingredient in hummus?', 'Lentils', 'Chickpeas', 'Beans', 'Peas', 'B'),
('Who wrote "The Great Gatsby"?', 'Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck', 'William Faulkner', 'B'),
('What is the currency of India?', 'Rupee', 'Riyal', 'Ringgit', 'Rupiah', 'A'),
('Which planet is known as the Morning Star?', 'Mars', 'Venus', 'Jupiter', 'Saturn', 'B'),
('What is the largest lake in Africa?', 'Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Chad', 'A'),
('Who painted the "Birth of Venus"?', 'Leonardo da Vinci', 'Michelangelo', 'Sandro Botticelli', 'Raphael', 'C'),
('What is the capital of Thailand?', 'Phuket', 'Chiang Mai', 'Bangkok', 'Pattaya', 'C'); 